### ISSUE TITLE
Rapid segfault on startup

### ISSUE THREAD

**Issue by greenrd** [bergie/blogsiple#6]
blogsiple segfaults soon after starting up, on Fedora 16. Here is a backtrace:

```
Thread 1 (Thread 0x7fa623621800 (LWP 11310)):
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x000000000041f802 in ?? ()
No symbol table info available.
#2  0x000000000046f36f in ev_invoke_pending ()
No symbol table info available.
#3  0x00000000004732d7 in ev_run ()
No symbol table info available.
#4  0x0000000000466bff in uv_run ()
No symbol table info available.
#5  0x0000000000423cc7 in node::Start(int, char**) ()
No symbol table info available.
#6  0x000000358da2169d in __libc_start_main (main=0x41e5d0 <main>, argc=3, ubp_av=0x7fffae754018, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffae754008) at libc-start.c:226
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -6719809158062976075, 4320044, 140736120307728, 0, 0, 6719702447469450165, -6713342673214942283}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7fffae754038, 0x1}, data = {prev = 0x0, cleanup = 0x0, canceltype = -1368047560}}}
        not_first_call = <optimized out>
#7  0x000000000041eb55 in _start ()
No symbol table info available.
```

**Comment by greenrd** [comment]
It seems this is a [general problem](http://lists.tchol.org/pipermail/nodejs-tchol.org/2012-April/000076.html) with Fedora 16 + node.js + Coffeescript, and not anything specific to blogsiple.
